### ISSUE TITLE
Long delay of fsck for complex filesystem

### ISSUE THREAD

**Issue by hyeongseok-kim901** [exfatprogs/exfatprogs#106]
Hello,
I have tested fsck.exfat 1.0.3 at master branch source code, with huge sdcard (512GB) after testing  fsstress about 3 days.
The fsstress generated about 80000 directory entries.

While checking, it takes about 200secs that is somewhat too long.
Profiling with blktrace, about 10GB has been read by 80961 read requests each for 128KiB which is the cluster size.

I wonder if it's possible to reduce read granularity to smaller than cluster size, e.g. 4KiB,
because not every directory file is filled with child entries.
I think fsck's speed can be improved if we can read directory entries with small size in incremental manner. (4KB -> next 4KB, not cluster size)
I have tried patching it, but it's difficult because reads of fsck is too much cluster base.

I attach blktrace for 128KiB (200sec/10GiB) vs 4KiB (44sec/320MiB) read iter setup.
About 4KiB read, I have locally patched by just changing read_size of iter to 4KiB in exfat_de_iter_init(),
and escape from read_children() when I met End-Of-Directory marker not to read for unused entries.
(Maybe, 4KiB read change worked for test only because my filesystem does not have too many siblings.)
Yes, additionally, in read_children(),
I wonder if we don't need to escape from while loop, when we met End-Of-Directory marker?

I hope it can be changed.
Thanks.

[blkparse_128k.tar.gz](https://github.com/exfatprogs/exfatprogs/files/4750457/blkparse_128k.tar.gz)
[blkparse_read_4k.tar.gz](https://github.com/exfatprogs/exfatprogs/files/4750462/blkparse_read_4k.tar.gz)

**Comment by hclee** [comment]
Hello @hyeongseok-kim901,
The size needs to be changed. and  I consider read-ahead and stoping the travel when the marker is met. 
Thank you.

**Comment by hyeongseok-kim901** [comment]
@hclee ,
Great !! Good to hear that.
When will it be released, v1.0.4 ? Do you have schedule? roughly?

**Comment by hclee** [comment]
@hyeongseok-kim901,
Sorry for the late reply.
I did the pull request #119 to solve this issues. Could you test it?
And we will release the next version within the next week.

**Comment by hyeongseok-kim901** [comment]
@hclee ,
Thanks. Improved.
Tested in approximately 20000 dir entried filesystem.
It read 2.7GB vs 1.2GB (current vs next), and took time as a half.

The request count is double of the current version, (21350 vs 40449)
and yes maybe it is due to reduce the request size.

Anyway, it have been improved, and I think it's good.

**Comment by namjaejeon** [comment]
Could you please share performance difference with other fsck utils ?

**Comment by hyeongseok-kim901** [comment]
@namjaejeon ,
I have shared performace data with @hclee , current vs next and including other commercial exfat tool.
Can you please discuss with him?
I can't currently look into the next version's changes in detail. 
Thanks.

**Comment by namjaejeon** [comment]
@hyeongseok-kim901 Okay! Thanks!

**Comment by hclee** [comment]
@hyeongseok-kim901 
We decreased the elapsed time. the time decreases from 24.95 seconds to 11.63 seconds in our test environment where we fill Samsung 64GB UHS-I sdcard with 9947 directories and 16504 files by fsstress.
If you want to check this, you can apply #122

**Comment by hclee** [comment]
@hyeongseok-kim901,
Could I close this issue?

**Comment by hyeongseok-kim901** [comment]
@hclee ,
Sorry for the late reply.
Sure, I think it's OK to close, I've checked the improvement.
Thanks.
