### ISSUE TITLE
-p option not documented for fsck

### ISSUE THREAD

**Issue by pablomh** [exfatprogs/exfatprogs#132]
I've noticed that `-p` option is not documented in [fsck.exfat.8](https://github.com/exfatprogs/exfatprogs/blob/master/manpages/fsck.exfat.8) man page
and I've tried to write a fix for it, but in order to do so I wanted to
understand the differences with `-y`.

To my undestanding `-y` always "fixes" what it can and `-p` depends on
a `ERF_PREEN_YES` flag that I don't understand where it comes from...

Could you please clarify so I can complete the man page?

**Comment by hclee** [comment]
Hello @pablomh,

> I've noticed that `-p` option is not documented in [fsck.exfat.8](https://github.com/exfatprogs/exfatprogs/blob/master/manpages/fsck.exfat.8) man page
> and I've tried to write a fix for it, but in order to do so I wanted to
> understand the differences with `-y`.
> 
> To my undestanding `-y` always "fixes" what it can and `-p` depends on
> a `ERF_PREEN_YES` flag that I don't understand where it comes from...
>
> Could you please clarify so I can complete the man page?

"-p" means if fsck can repair any problems safely, let fsck fix those
automatically without user interaction.

**Comment by hclee** [comment]
This issue is solved in PR #133
