### ISSUE TITLE
The exfat dichotomy

### ISSUE THREAD

**Issue by papadakospan** [exfatprogs/exfatprogs#136]
There's https://github.com/relan/exfat:
- provides a FUSE driver (not needed in recent versions of the linux kernel)
- doesn't provide a tune utility

And this project (https://github.com/exfatprogs/exfatprogs) which is driven by Samsung, AFAIK:
- uses the native kernel driver
- doesn't provide a labeling utility, for example.

It would be really helpful to see some kind of merger here. It was sort of mentioned in relan/exfat#151

**Comment by namjaejeon** [comment]
exfatprogs support setting volume label using mkfs.exfat and tune.exfat. exfatprogs doesn't have dump.exfat yet, we are planning to work it soon. and exfatprogs provide much better fsck than fuse-exfat's one. So I don't think that exfatprogs is merged with fuse-exfat.

**Comment by papadakospan** [comment]
Awesome! I didn't know you could set the label with tune. The standard way is to (also) have some utility like <fs>label.
In that case, exfatprogs covers me for labeling. Maybe you could have that utility as an alias to tune -L?

As an example, gnome-disks was looking to use a exfatlabel utility, to rename a partition, but that utility isn't provided immediattely by exfatprogs. Good to know I can change labels as-is though.

thanks

**Comment by hclee** [comment]
As namjae said, we are going to implement corruption repair and dump.exfat, and etc. At least we can complete these features until  the third quarter of next year.

**Comment by namjaejeon** [comment]
> Maybe you could have that utility as an alias to tune -L?

@papadakospan Could you please check README ?

- tune.exfat:
    Adjust tunable filesystem parameters on an exFAT filesystem

Usage example:
    1. print current volume label.
        tune.exfat -l /dev/sda1
    2. set new volume label.
        tune.exfat -L "new label" /dev/sda1

To set volume label, -L option is already used.

**Comment by papadakospan** [comment]
Yes of course I checked the manpage, It the reason I learned OF the `-L` option. What I'm suggesting is a separate program named `exfatlabel`, that would do the same thing as `tune -L`, because every filesystem has it as a utility and users will expect it and get jobs done quicker.

**Comment by namjaejeon** [comment]
hm, what is *tune* util ? Is it contained in utils-linux ?

**Comment by papadakospan** [comment]
I mean your tune utility, `tune.exfat -L`

**Comment by namjaejeon** [comment]
OK, Will take a look!

**Comment by namjaejeon** [comment]
@papadakospan exfatlabel has been applied to exfat-next. please check it (https://github.com/exfatprogs/exfatprogs/pull/137). Thanks!

**Comment by papadakospan** [comment]
Thanks! Just used `exfatprogs` yesterday for a new SD card!
