### ISSUE TITLE
[tools][feature request] Allow To Change Volume Serial Number ("ID")

### ISSUE THREAD

**Issue by maddes-b** [exfatprogs/exfatprogs#138]
Please consider adding a separate tool or extending the label tool to change the volume serial number of an exFAT file system (offset 0x64/100 in main boot sector).
For FAT under Linux one can use `mlabel -N 12345678 -i /dev/sdb1`.

**Comment by namjaejeon** [comment]
Okay. I will add -i option in exfatlabel.

**Comment by namjaejeon** [comment]
@maddes-b We have committed a volume serial set patch to #exfat-next branch.(https://github.com/exfatprogs/exfatprogs/commit/b4d9c9eeb5c28b503e103e2c4ec22bc146446d9f)

Please check it work fine as you expected.
```
$ sudo exfatlabel -i /dev/sdb1 0x1234
exfatprogs version : 1.0.4
New volume serial : 0x1234

$ sudo exfatlabel -i /dev/sdb1
exfatprogs version : 1.0.4
volume serial : 0x1234
```

**Comment by maddes-b** [comment]
For end users you should note that the new serial should be entered in hex-decimal, e.g. "0x12345678" instead of "12345678" or "1234-5678".
Side note: The README misses `make` as a prerequisite. Maybe common to developers, but maybe not to all contributors wanting to test.

Working well in my tests.

**Comment by namjaejeon** [comment]
Thanks for your review!

> Side note: The README misses make as a prerequisite. Maybe common to developers, but maybe not to all contributors wanting to test.

Where is missing "make" ? You are saying "Build steps" section ?

**Comment by maddes-b** [comment]
On a clean Ubuntu 20.10 when just installing the packages from README.md...
```
For Ubuntu:
    sudo apt-get install autoconf libtool pkg-config
```
, then `make` is missing on the system.

P.S.: Already closing the issue as the main topic has been implemented.

**Comment by namjaejeon** [comment]
Okay, Thanks for your answer and Let me know it if you have any issue.
