### ISSUE TITLE
[feature request] File system usage reporting

### ISSUE THREAD

**Issue by mfleetwo** [exfatprogs/exfatprogs#139]
Please add file system usage reporting of unmounted exfat file systems into one of the command line tools.  Probably extend `tune.exfat -v` output.

Note that the Linux kernel exfat implementation, [exfat_statfs()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/fs/exfat/super.c?h=v5.10.12#n72), already provides this when the file system is mounted for the [statfs(2)](https://man7.org/linux/man-pages/man2/statfs.2.html) call.

All other Linux file system tools provide some way to report total number of blocks / clusters and used or available blocks / clusters.

My particular reason is so that I can make [GParted](https://gparted.org/) report the usage of unmounted exfat file systems to users.

Thanks,
Mike Fleetwood (GParted Developer)

**Comment by namjaejeon** [comment]
I agreed your suggestion.

> All other Linux file system tools provide some way to report total number of blocks / clusters and used or available blocks / clusters.
Before working it, Could you please give us more detail example from other filesystem tools ? Which file system tool supports it? and which option does it define ? I would like to check if tune.exfat is proper place or not.

Thanks!

**Comment by mfleetwo** [comment]
There is no standardised way of querying file system usage for different file system types, as can be seen from the examples below.  They do all provide a method though.

exfatprogs already provides file system size information, but not yet the usage:
```
# tune.exfat -v /dev/sdb1
exfatprogs version : 1.0.4
[exfat_get_blk_dev_info: 177] Block device name : /dev/sdb1
[exfat_get_blk_dev_info: 178] Block device size : 1073741824
[exfat_get_blk_dev_info: 179] Block sector size : 512
[exfat_get_blk_dev_info: 180] Number of the sectors : 2097152
[exfat_get_blk_dev_info: 180] Number of the clusters : 32768
```


Other file system examples:

1. btrfs using [btrfs filesystem(8)](https://man7.org/linux/man-pages/man8/btrfs-filesystem.8.html) `show`
   ```
   # btrfs filesystem show /dev/sdb1 | egrep 'size|used'
           Total devices 1 FS bytes used 172.38MiB
           devid    1 size 1.00GiB used 350.38MiB path /dev/sdb1
   ```
2. ext2/3/4 using [tune2fs(8)](https://man7.org/linux/man-pages/man8/tune2fs.8.html) `-l List the contents of the file system superblock`
   ```
   # tune2fs -l /dev/sda7 | egrep 'Block count|Free blocks|Block size'
   Block count:              78643200
   Free blocks:              6653121
   Block size:               4096
   ```
3. ext2/3/4 using [dumpe2fs(8)](https://man7.org/linux/man-pages/man8/dumpe2fs.8.html) `-h only display the superblock information ...`
   Note: `tune2fs -l` == `dumpe2fs -h`
   ```
   # dumpe2fs -h /dev/sda7 2> /dev/null | egrep 'Block count|Free blocks|Block size'
   Block count:              78643200
   Free blocks:              6653121
   Block size:               4096
   ```
4. f2fs using [dump.f2fs(8)](https://manpages.debian.org/testing/f2fs-tools/dump.f2fs.8.en.html) `-d debug-level`
   ```
   # dump.f2fs -d 1 /dev/sdb1 | egrep 'user_block_count|valid_block_count|log_blocksize|Info: sector size =|Info: total FS sectors ='
   Info: sector size = 512
   log_blocksize                 		[0x       c : 12]
   Info: total FS sectors = 2097152 (1024 MB)
   user_block_count              		[0x   36400 : 222208]
   valid_block_count             		[0x    7b14 : 31508]
   ```
5. fat16/32 using [mdir(1)](https://www.gnu.org/software/mtools/manual/mtools.html#mdir) and [minfo(1)](https://www.gnu.org/software/mtools/manual/mtools.html#minfo)
   Note: `-i IMAGEFILE :` is `mtools` way of specifying a device name directly rather than using a drive letter to make MSDOS users feel at home.
   ```
   # mdir -i /dev/sdb1 ::/ | egrep 'bytes free$'
                           888 127 488 bytes free
   # minfo -i /dev/sdb1 :: | egrep 'sector size|cluster size|small size|big size'
   sector size: 512 bytes
   cluster size: 8 sectors
   small size: 0 sectors
   big size: 2097152 sectors
   ```
6. ntfs using [ntfsinfo(8)](https://linux.die.net/man/8/ntfsinfo) `--mft Show information about the volume`
   ```
   # ntfsinfo --mft --force /dev/sdb14 | egrep 'Cluster Size|Volume Size in Clusters|Free Clusters'
	   Cluster Size: 4096
	   Volume Size in Clusters: 65535
	   Free Clusters: 23405 (35.7%)
   ```
7. udf using [udfinfo(1)](https://man7.org/linux/man-pages/man1/udfinfo.1.html)
   ```
   # udfinfo --utf8 /dev/sdb2 | egrep '^blocksize=|^blocks=|^usedblocks=|^freeblocks=|^behindblocks='
   blocksize=512
   blocks=2097152
   usedblocks=700605
   freeblocks=1396033
   behindblocks=0
   ```
8. xfs using [xfs_db(8)](https://man7.org/linux/man-pages/man8/xfs_db.8.html)
   ```
   # xfs_db -r -c 'sb 0' -c 'print blocksize' -c 'print dblocks' -c 'print fdblocks' /dev/sdb14
   blocksize = 4096
   dblocks = 65536
   fdblocks = 23042
   ```

**Comment by namjaejeon** [comment]
@mfleetwo Okay. I will start to work it. Thanks for detail answer!

**Comment by mfleetwo** [comment]
And here is how [exfat-utils](https://github.com/relan/exfat) does it with [dumpexfat(1)](http://manpages.ubuntu.com/manpages/focal/man8/dumpexfat.8.html)
1. FS size
   ```
   # dumpexfat /dev/sdb13 | egrep 'Sector size|Sectors count'
   Sector size                      512
   Sectors count                 524288
   ```
2. FS usage
   ```
   # dumpexfat /dev/sdb13 | egrep 'Cluster size|Clusters count|Free clusters'
   Cluster size                    4096
   Clusters count                 65024
   Free clusters                  23585
   ```

**Comment by namjaejeon** [comment]
Yes, dump.exfat -v would be better.

**Comment by mfleetwo** [comment]
That does contain the information that is needed for determining exFAT usage.

However all the tools report usage / availability in units of the smallest allocatable size for their file system.  Unix file systems call this the block size and Windows file systems call it the cluster size.  So I suggest reporting the exFAT usage figures in units of cluster size, not sectors.  See exfat-utils and ntfs examples above.

**Comment by namjaejeon** [comment]
Agreed:) I will update it and inform you if the patch is merged into master.

**Comment by namjaejeon** [comment]
We have release exfatprogs 1.1.0 version. You can use this release. If you have any issue, Let me know it.

**Comment by namjaejeon** [comment]
@mfleetwo You sent the patch("dump.exfat: exit with status 0 on success") to us. Thanks for the patch!  Are you waiting for exfatprogs 1.1.1 release that is committed this patch? I wonder if we should release 1.1.1 that includes this patch right now in order to use dump.exfat at GParted.

**Comment by mfleetwo** [comment]
Thank you for asking.  No, I am not waiting for patch "dump.exfat: exit with status 0 on success" to be in a release of exfatprogs.

GParted is just going to check stderr is non-empty to determine failure.  I think this is the simplest solution.  To do otherwise is going to require either more coding to check for exfatprogs >= 1.1.1, or documenting the same which can be ignored.

* exfat::set_used_sectors() in GParted pending commit [Add exFAT file system usage reporting (!67)](https://gitlab.gnome.org/GNOME/gparted/-/merge_requests/67/diffs?commit_id=b82b8eccbdb1bed9b43298d116c3ed23e798cbc4)
* GParted pending merge request [Add support for reading exFAT usage and updating the UUID](https://gitlab.gnome.org/GNOME/gparted/-/merge_requests/67)

**Comment by namjaejeon** [comment]
@mfleetwo Sound great! If your issue is clear, Could you please close this issue ? Thanks for your help!

**Comment by mfleetwo** [comment]
Exfat usage reporting works.  Changes to GParted were merged as a
result.

Closing issue.
Thanks,
Mike Fleetwood (GParted Developer)
