### ISSUE TITLE
Can't recover corrupted boot region with 1.1.0

### ISSUE THREAD

**Issue by rooiratel** [exfatprogs/exfatprogs#150]
Hi, according to https://github.com/exfatprogs/exfatprogs/releases/tag/1.1.0 we should now be able to recover a corrupted boot region with version 1.1.0

I installed the new version but it won't allow me to select y to fix the boot region. It just assumes N and skips it.

I'm using Arch Linux, using the exfatprogs package version 1.1.0-1

Here is a screenshot of my terminal output when I try to repair the boot region on my external drive:

![image](https://user-images.githubusercontent.com/34131729/107872638-3e1a1f00-6eb4-11eb-8169-44c42a6bbe6b.png)

**Comment by hclee** [comment]
Hello @rooiratel 
you should provide -y option. Please refer to fsck.exfat (8) manpage

**Comment by rooiratel** [comment]
Thanks @hclee 

Doing : `sudo fsck.exfat -y /dev/sdd`  worked and it repaired the drive without any issues.

I was just confused because normally when a command line application asks (y/N) I expect it to wait for me to give it input. 

Reading the man pages the -r option is what I assumed it would do by default.

Maybe remove the (y/N) question from the output if you are not running it in interactive mode, to reduce confusion.

Anyway, thanks for the help. Much appreciated.
