### ISSUE TITLE
Invalid boot checksum after formatting an Advanced Format 4K native HDD

### ISSUE THREAD

**Issue by cvubrugier** [exfatprogs/exfatprogs#163]
Hi,

I observe that mounting an exFAT file system formatted with exfatprogs fails if the underlying device is an [Advanced Format, 4K
native](https://en.wikipedia.org/wiki/Advanced_Format) HDD. 4K native HDDs report both a physical and logical block size equal to 4 KB.

Below are the properties of a 4Kn disk emulated with QEMU:

    $ lsblk --topology /dev/vda
    NAME ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED       RQ-SIZE  RA WSAME
    vda          0   4096      0    4096    4096    1 mq-deadline     256 128    0B

Formatting the device with exfatprogs' `mkfs.exfat` succeeds. The block sector size is correctly probed as 4096 bytes:

    $ sudo mkfs/mkfs.exfat -v /dev/vda
    exfatprogs version : 1.1.1
    [exfat_get_blk_dev_info: 202] Block device name : /dev/vda
    [exfat_get_blk_dev_info: 203] Block device offset : 0
    [exfat_get_blk_dev_info: 204] Block device size : 21474836480
    [exfat_get_blk_dev_info: 205] Block sector size : 4096
    [exfat_get_blk_dev_info: 206] Number of the sectors : 41943040
    [exfat_get_blk_dev_info: 208] Number of the clusters : 655360
    [exfat_zero_out_disk: 505] zero out written size : 4358144, disk size : 21474836480
    Creating exFAT filesystem(/dev/vda, cluster size=32768)

    Writing volume boot record: [exfat_setup_boot_sector:  80] Volume Offset(sectors) : 0
    [exfat_setup_boot_sector:  82] Volume Length(sectors) : 5242880
    [exfat_setup_boot_sector:  84] FAT Offset(sector offset) : 256
    [exfat_setup_boot_sector:  86] FAT Length(sectors) : 640
    [exfat_setup_boot_sector:  88] Cluster Heap Offset (sector offset) : 1024
    [exfat_setup_boot_sector:  90] Cluster Count : 655232
    [exfat_setup_boot_sector:  92] Root Cluster (cluster offset) : 6
    [exfat_setup_boot_sector:  94] Volume Serial : 0x6ddeb17c
    [exfat_setup_boot_sector:  95] Sector Size Bits : 12
    [exfat_setup_boot_sector:  97] Sector per Cluster bits : 3
    done
    Writing backup volume boot record: [exfat_setup_boot_sector:  80] Volume Offset(sectors) : 0
    [exfat_setup_boot_sector:  82] Volume Length(sectors) : 5242880
    [exfat_setup_boot_sector:  84] FAT Offset(sector offset) : 256
    [exfat_setup_boot_sector:  86] FAT Length(sectors) : 640
    [exfat_setup_boot_sector:  88] Cluster Heap Offset (sector offset) : 1024
    [exfat_setup_boot_sector:  90] Cluster Count : 655232
    [exfat_setup_boot_sector:  92] Root Cluster (cluster offset) : 6
    [exfat_setup_boot_sector:  94] Volume Serial : 0x6ddeb17c
    [exfat_setup_boot_sector:  95] Sector Size Bits : 12
    [exfat_setup_boot_sector:  97] Sector per Cluster bits : 3
    done
    Fat table creation: [exfat_create_fat_table: 296] Total used cluster count : 7
    done
    Allocation bitmap creation: done
    Upcase table creation: done
    Writing root directory entry: done
    Synchronizing...

    exFAT format complete!

However, mounting the exFAT filesystem fails. The Linux kernel reports an _Invalid boot checksum_ error.

    $ sudo mount /dev/vda /mnt/
    [  262.063000] exFAT-fs (vda): Invalid boot checksum (boot checksum : 0x8455546b, checksum : 0xfedcaae5)
    [  262.068991] exFAT-fs (vda): invalid boot region
    [  262.071618] exFAT-fs (vda): failed to recognize exfat type
    mount: /mnt: wrong fs type, bad option, bad superblock on /dev/vda, missing codepage or helper program, or other error.

Moreover, `fsck.exfat` reports the same issue:

    $ sudo fsck/fsck.exfat /dev/vda
    exfatprogs version : 1.1.1
    checksum of boot region is not correct. 0x8455546b, but expected 0xfedcaae5
    boot region is corrupted. try to restore the region from backup. Fix (y/N)? n

I am going to investigate and will report on my findings later.

**Comment by namjaejeon** [comment]
Okay, Can you check if bd->sector_size is not 4096 ?
int exfat_get_blk_dev_info(struct exfat_user_input *ui,
		struct exfat_blk_dev *bd)
...
	if (ioctl(fd, BLKSSZGET, &bd->sector_size) < 0)
		bd->sector_size = DEFAULT_SECTOR_SIZE;

**Comment by namjaejeon** [comment]
Sound good!

**Comment by cvubrugier** [comment]
Fixed
=

This issue and other issues observed with 4Kn HDDs and reported by @sandeen on the Linux [fsdevel mailing list](https://lore.kernel.org/linux-fsdevel/372ffd94-d1a2-04d6-ac38-a9b61484693d@sandeen.net/) are fixed by the following commits:

* [dump: use BytesPerSectorShift of boot sector](https://github.com/exfatprogs/exfatprogs/commit/7037652)
* [fsck: use BytesPerSectorShift of boot sector to verify boot region](https://github.com/exfatprogs/exfatprogs/commit/478f39f)
* [exfatprogs: libexfat: fix wrong bd->num_sectors calculation](https://github.com/exfatprogs/exfatprogs/commit/3b3025c)
* [exfatprogs: tune: use sector size extracted from the boot sector](https://github.com/exfatprogs/exfatprogs/commit/a13479b)
* [mkfs: fix boot sector checksum when the sector size is 4 KB](https://github.com/exfatprogs/exfatprogs/commit/1e3163a)

These changes are included in exfatprogs [1.1.2](https://github.com/exfatprogs/exfatprogs/releases/tag/1.1.2).
