### ISSUE TITLE
fsck:fix double free of exfat pointer

### ISSUE THREAD

**Issue by yijiangqiu1** [exfatprogs/exfatprogs#176]
in function init_exfat(exfat,bs),if it fails to calloc memory,it will call function free_exfat and return -ENOMEM. Thus it will goto err in main function and call free_exfat(exfat) again.
      As follows:
           main
             ->init_exfat(exfat,bs)
               ->free_exfat(exfat)
                 return -ENOMEM
             ->free_exfat(exfat)

**Comment by yijiangqiu1** [comment]
A solution of this problem may be as follows:
       `ret = init_exfat(exfat, bs);
       if (ret) {
               exfat=NULL;
                goto err;
       }
`

**Comment by namjaejeon** [comment]
Please send the pull request included patches to #exfat-next branch in exfatprogs.
