### ISSUE TITLE
fsck: fix Out-of-Bounds Accesses in function bytes_to_human_readable

### ISSUE THREAD

**Issue by yijiangqiu1** [exfatprogs/exfatprogs#177]
In function bytes_to_human_readable, if bytes > 1024PB, the variable named i will be 6 and  in “snprintf(buf, sizeof(buf), "%u.%02u %s", quoti, remain, units[i]);”，function will access units[6] . This will cause Out-of-Bounds Accesses.

**Comment by namjaejeon** [comment]
Please send the pull request included patches to #exfat-next branch in exfatprogs.

**Comment by yijiangqiu1** [comment]
One solution maybe like this:
![image](https://user-images.githubusercontent.com/36325255/140005867-2b1504aa-12c9-4079-9611-5736286a3519.png)

**Comment by yijiangqiu1** [comment]
One solution maybe like this:

**Comment by namjaejeon** [comment]
Okay, Do you know how to send pull request  ?

**Comment by yijiangqiu1** [comment]
I am trying to learn it

**Comment by namjaejeon** [comment]
Sound good, Please reference how other developers did work it. https://github.com/exfatprogs/exfatprogs/pull/175

**Comment by hclee** [comment]
@yijiangqiu1 
If you have trouble with sending a pull request, I will push your commits. Can you tell me your email address for signed-by in commit description?

**Comment by yijiangqiu1** [comment]
sorry, I am busy with other things last week

**Comment by yijiangqiu1** [comment]
@hclee thanks. I have done it.https://github.com/exfatprogs/exfatprogs/pull/178
