### ISSUE TITLE
Full format without --full-format ?

### ISSUE THREAD

**Issue by lejeczek** [exfatprogs/exfatprogs#186]
Hi
Is mkfs.exfat doing full format without being asked for it? It seems like it.
thanks, L
exfatprogs-1.1.2-2.fc35.x86_64
It takes 'mkfs.exfat ' ages.
many thanks, L.

**Comment by hclee** [comment]
> Hi Is mkfs.exfat doing full format without being asked for it? It seems like it.
Yes, mkfs.exfat creates an exfat file system without asking the user.
What is "full format"?, and where does the option, "--full-format" come from?

**Comment by lejeczek** [comment]
From 'man' page for mkfs.exfat of the version I mentioned above.
...
       -f, --full-format
              Performs  a full format.  This zeros the entire disk device while creating the
              exFAT filesystem.
...

**Comment by namjaejeon** [comment]
no response. closed.
