### ISSUE TITLE
Exfatprogs Release Signing Key has expired

### ISSUE THREAD

**Issue by Bonnietwin** [exfatprogs/exfatprogs#187]
I did a gpg --verify on the  exfatprogs-1.1.3.tar.xz.asc  file and it said it was a good signature but it also said that the key had expired.

**Comment by hclee** [comment]
I have renewed the key. Can you update it and try the verification again?

**Comment by Bonnietwin** [comment]
I have renewed the key and now the verification works with no problems. Thanks very much.

I am closing this issue now.
