### ISSUE TITLE
exfat-fs fails with a Windows-formatted drive

### ISSUE THREAD

**Issue by fijam** [exfatprogs/exfatprogs#188]
Hi,

I suppose this is a kernel driver bug, but I hope by filing it here it will reach the correct people.

I have formatted a 3TB drive in USB enclosure under Windows 10 21H1 (OS Build 19043.1348) as exFAT.

I try to use it on a Linux device with kernel 5.15.5 and exfatprogs 1.1.3.

Connecting the drive:
```
[94326.044840] usb-storage 2-1:1.0: USB Mass Storage device detected
[94326.054889] scsi host2: usb-storage 2-1:1.0
[94336.077012] scsi 2:0:0:0: Direct-Access     ATA      WDC WD30PURX-64P 0A80 PQ: 0 ANSI: 6
[94336.078337] sd 2:0:0:0: [sdb] Very big device. Trying to use READ CAPACITY(16).
[94336.078524] sd 2:0:0:0: [sdb] 5860533168 512-byte logical blocks: (3.00 TB/2.73 TiB)
[94336.078535] sd 2:0:0:0: [sdb] 4096-byte physical blocks
[94336.079218] sd 2:0:0:0: [sdb] Write Protect is off
[94336.079229] sd 2:0:0:0: [sdb] Mode Sense: 43 00 00 00
[94336.079844] sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[94336.366187]  sdb: sdb1 sdb2
[94336.368370] sd 2:0:0:0: [sdb] Attached SCSI disk
```

Mounting the drive:
```
[95338.486473] exFAT-fs (sdb1): invalid boot record signature
[95338.486491] exFAT-fs (sdb1): failed to read boot sector
[95338.486496] exFAT-fs (sdb1): failed to recognize exfat type
```

exfatprogs utilities:

```
fsck.exfat -n /dev/sdb1
exfatprogs version : 1.1.3
failed to find exfat file system
boot region is corrupted. try to restore the region from backup. Fix (y/N)? n
```

```
tune.exfat -v /dev/sdb1
exfatprogs version : 1.1.3
[exfat_get_blk_dev_info: 202] Block device name : /dev/sdb1
[exfat_get_blk_dev_info: 203] Block device offset : 17408
[exfat_get_blk_dev_info: 204] Block device size : 134217728
[exfat_get_blk_dev_info: 205] Block sector size : 512
[exfat_get_blk_dev_info: 206] Number of the sectors : 262144
[exfat_get_blk_dev_info: 208] Number of the clusters : 32768
```

```
dump.exfat /dev/sdb1
exfatprogs version : 1.1.3
bogus sector size bits : 0
```

Please let me know if you need more information.

**Comment by namjaejeon** [comment]
Can you show me the value after commanding the below ?

# cat /sys/block/sda/queue/hw_sector_size

**Comment by fijam** [comment]
```
cat /sys/block/sdb/queue/hw_sector_size
512
```

**Comment by namjaejeon** [comment]
Please do this also.

$ lsblk --topology /dev/vda
NAME ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED       RQ-SIZE  RA WSAME
vda          0   4096      0    4096    4096    1 mq-deadline     256 128    0B

**Comment by fijam** [comment]
```
# lsblk --topology /dev/sdb
NAME   ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED       RQ-SIZE  RA WSAME
sdb            0   4096      0    4096     512    1 mq-deadline       2 128    0B
├─sdb1      3072   4096      0    4096     512    1 mq-deadline       2 128    0B
└─sdb2         0   4096      0    4096     512    1 mq-deadline       2 128    0B
```

**Comment by namjaejeon** [comment]
okay.  Could you please try to mount after formatting your usb drive using mkfs.exfat ?

**Comment by fijam** [comment]
I can, but I need to back up the data first. It will take a few hours. I will report back!

**Comment by namjaejeon** [comment]
Ah..Okay, no need to do it if you need backup.

**Comment by namjaejeon** [comment]
@cvubrugier Could you please help me fix this issue ? I don't have this type of HDD.
His hard has 4K hw sector and 512B logical sector. I wonder if this difference is causing this issue.
Do you have this type of HDD drive ?

**Comment by namjaejeon** [comment]
@fijam if you try to mount  /dev/sdb2 ?

**Comment by fijam** [comment]
Mounting sdb2 in fact works! Although I don't understand why Windows creates two volumes (the drive only appears as one volume in Windows).

Apologies for the trouble.

**Comment by cvubrugier** [comment]
@namjaejeon wrote:
> @cvubrugier Could you please help me fix this issue ? I don't have this type of HDD.
> His hard has 4K hw sector and 512B logical sector. I wonder if this difference is causing this issue.
> Do you have this type of HDD drive ?

I could arrange for that. Most modern HDDs have 4 KB sectors but emulate 512 bytes sectors ([512e](https://en.wikipedia.org/wiki/Advanced_Format#512_emulation_(512e))) so that even firmware or OSes that do not support 4 KB sectors can work with them.

I guess the problem reported by @fijam is not caused by the HDD sector size.

> dump.exfat /dev/sdb1
> exfatprogs version : 1.1.3
> bogus sector size bits : 0

I think sector size bits should be 9 (`1 << 9 == 512`).

> tune.exfat -v /dev/sdb1
> exfatprogs version : 1.1.3
> [exfat_get_blk_dev_info: 202] Block device name : /dev/sdb1
> [exfat_get_blk_dev_info: 203] Block device offset : 17408
> [exfat_get_blk_dev_info: 204] Block device size : 134217728

So the size of the first partition is 128 MiB whereas the HDD capacity is 3 TB. This looks like an [EFI System Partition](https://en.wikipedia.org/wiki/EFI_system_partition).

> Mounting sdb2 in fact works! Although I don't understand why Windows creates two volumes (the drive only appears as one volume in Windows).

This is consistent with our guess that the first partition is an EFI System Partition.

@fijam, could you run the following command? With that, we can verify if the first partition is an EFI System Partition.

    $ sudo blkid /dev/sdb1

**Comment by fijam** [comment]
Looks like you got it right:

```
# blkid /dev/sdb1
/dev/sdb1: PARTLABEL="Microsoft reserved partition" PARTUUID="69faad38-f483-4939-a7bf-c7d6cef4828b"
```

**Comment by cvubrugier** [comment]
Maybe the exfatprogs utilities do not display an error if the file system magic does not match the one for exFAT.

In your situation, I think `fsck.exfat`, `dump.exfat`, and `tune.exfat` should have warned you that it is _not_ an exFAT file system. Instead of that, the commands reported that the file system was corrupted.

There is probably room for improvement here.

**Comment by namjaejeon** [comment]
@cvubrugier Fully agreed:)

**Comment by hclee** [comment]
@cvubrugier 
Thank you for comments. I will fix it.
