### ISSUE TITLE
kernel 3.10.14 is not useful!

### ISSUE THREAD

**Issue by yjr1220** [exfatprogs/exfatprogs#192]
hello ! 

            I compile the code with mips cross compile tool ，but the mkfs.exfat can not work normal !  what' wrong ?  my kernel version is 3.10.14 .       

                  thanks a lot!

**Comment by yjr1220** [comment]
kernel need config ?

**Comment by hclee** [comment]
Can you tell us in detail?

**Comment by namjaejeon** [comment]
no reply for long time.
