### ISSUE TITLE
mkfs: Documenting default for --boundary-align and --cluster-size 

### ISSUE THREAD

**Issue by Artoria2e5** [exfatprogs/exfatprogs#220]
mkfs.exfat.8 currently has a recommendation table from the SD association for these two options, but does not actually describe what this program does by default via https://github.com/exfatprogs/exfatprogs/blob/3228312ffeff051870de9178b893f5676ed5e773/lib/libexfat.c#L138-L139

Specifically, the default boundary alignment is fixed at 1 MiB, and the default cluster size is set in https://github.com/exfatprogs/exfatprogs/blob/3228312ffeff051870de9178b893f5676ed5e773/lib/libexfat.c#L120-L121

**Comment by namjaejeon** [comment]
@Artoria2e5 I'd really appreciate if you contribute a patch for this.

**Comment by namjaejeon** [comment]
Applied your patch to linux-next. Closed THE ISSUE.
