### ISSUE TITLE
Setting of the InUse bit of EntryType of Volume Label Entry

### ISSUE THREAD

**Issue by jengbou** [exfatprogs/exfatprogs#230]
While using [The Sleuth Kit (TSK)](https://www.sleuthkit.org/sleuthkit/) to analyze flash drives formatted without a label using mkfs.exfat, I encountered this error:

> exfatfs_is_vol_label_dentry: incorrect volume label length

Which was caused by the label length check at [L128 of exfatfs_meta.c](https://github.com/sleuthkit/sleuthkit/blob/sleuthkit-4.12.0/tsk/fs/exfatfs_meta.c#L128) because the default value (0x83) of the EntryType in mkfs.c indicates that the Volume Label Entry is in use even if there is really no label provided when formatting:
https://github.com/exfatprogs/exfatprogs/blob/8593314715f4c0e531ee7cb26bdd4cd06e8a3f7f/mkfs/mkfs.c#L345
https://github.com/exfatprogs/exfatprogs/blob/8593314715f4c0e531ee7cb26bdd4cd06e8a3f7f/include/exfat_ondisk.h#L54

However, my understanding is that if the formatted volume does not have a label, the InUse bit of the EntryType should be set to 0 (i.e., EntryType should be 0x03) instead of 1 (0x83) according to Microsoft's exFAT specification[^1][^2]. Windows Disk Management does set this bit accordingly, so the TSK commands work fine with those formatted by Windows. Although TSK could improve their check for wider compatibility, I think it makes sense to also modify L345 in mkfs.c to something like:

`ed[0].type = ui->volume_label_len > 0 ? EXFAT_VOLUME : 0x03;`

Please let me know if this sounds a reasonable suggestion or if there is something obvious I missed. Thank you!

[^1]: https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#table-15-generic-entrytype-field-structure
[^2]: https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#6214-inuse-field).

**Comment by namjaejeon** [comment]
@jengbou Okay, Looks reasonable to me. Can you give us a PR(pull request included the patch) for this ?
