### ISSUE TITLE
BPB sector size field should be user selectable

### ISSUE THREAD

**Issue by ChrisPVille** [exfatprogs/exfatprogs#247]
When creating a new filesystem with `mkfs.exfat`, the BIOS Parameter Block sector size field (`sect_size_bits`) is filled based on the target block device's block size. This is normally fine except I'm generating an exfat image into a file for use on a device with a different sector size than my filesystem.

As a result, the exfat image has a fixed 9 (512 bytes), making it unsuitable for flashing onto a flash where the sector size is larger.  A solution used by other mkfs utilities is to allow the user to override the BPB sector size field.

**Comment by namjaejeon** [comment]
@ChrisPVille Can you fix it and contribute the patch to exfatprogs project ?

**Comment by ChrisPVille** [comment]
I'll take a look when I get a chance. There's at least a few sanity checks that will need to happen with a mix of auto and manually specified sector given the cylinder option

**Comment by namjaejeon** [comment]
@ChrisPVille Please close if it is improved on new exfatprogs-1.2.3 version.
