### ISSUE TITLE
Assets and virustotal

### ISSUE THREAD

**Issue by uli-heller** [exfatprogs/exfatprogs#273]
Hey, I downloaed various assets and checked them via virustotal.com. For some of them, I got an alert
for

  Antiy-AVL - Trojan[ArcBomb]/Win32.Agent

I downloaded these assets for various versions:

- XZ: https://github.com/exfatprogs/exfatprogs/releases/download/1.2.5/exfatprogs-1.2.5.tar.xz
- GZ: https://github.com/exfatprogs/exfatprogs/archive/refs/tags/1.2.5.tar.gz

I get this virus matrix:

version | xz | gz
----------|---|----
1.2.2 | - | V
1.2.3 | - | V
1.2.4 | - | V
1.2.5 | V | V

"V" means virustotal detected something

What shall I do?

**Comment by namjaejeon** [comment]
Which files are causing the problem when decompressing compressed releases?

**Comment by uli-heller** [comment]
I cannot see any file causing an issue. I think it is the archive which triggers virustotal:
https://www.virustotal.com/gui/file/f27160dcc1ddd17c96cd41a6ceef7037adc2796ab5c5633d3d85cf532c3ee2f0/detection

**Comment by namjaejeon** [comment]
Can you run this test after decompressing ? I want to know which file cause this issue.

**Comment by uli-heller** [comment]
I will try to do so but it will take quite some time. For each file, it takes a minute or two or more to get the results from virustotal.

**Comment by namjaejeon** [comment]
@uli-heller Okay, Thanks for your help!

**Comment by namjaejeon** [comment]
When I have tried to run V3 lite against exfatprogs-1.2.5.tar.xz on windows, there is no virus detection.

**Comment by uli-heller** [comment]
It is one (or more) of the files below tests. I'm still investigating

**Comment by uli-heller** [comment]
Looking at the .tar.xz files provided for the releases I realize that

- up until and including 1.2.4, the archive doesn't contain the tests folder
- 1.2.5 includes the tests folder
- packaging just the tests folder leads to a detection within virustotal
- splitting the tests folder into two halfs and packaging each half leads to a detection within virustotal for the first half only
- uploading all the individual files within the tests folder onto virustotal does NOT lead to a detection. It seems to be necessary to package them within a tar file (I'll double-check on this)

**Comment by uli-heller** [comment]
It becomes better and better:

- 2.tar ... shows a virus
- 21.tar ... does NOT show a virus
- 22.tar ... does NOT show a virus
- 21.tar + 22.tar = 2.tar

All files are included within the ZIP.

[2.zip](https://github.com/user-attachments/files/16550311/2.zip)

**Comment by namjaejeon** [comment]
@uli-heller Okay, Can we think there is no issue? right?

**Comment by hclee** [comment]
> Looking at the .tar.xz files provided for the releases I realize that
> 
>     * up until and including 1.2.4, the archive doesn't contain the tests folder

Regardless of the version, gzipped archives always are detected to have virus by Antiy-AVL.

Only Antiy-AVL out of dozens of security vendors detect this, Can it be false-positive?

**Comment by namjaejeon** [comment]
If you have some issue, please reopen it.
