### ISSUE TITLE
mkfs.exfat: Volume-GUID format undocumented?

### ISSUE THREAD

**Issue by luziferius** [exfatprogs/exfatprogs#275]
I want to in-place re-create an exFAT file system, and to not need to rewrite UUIDs in `/etc/fstab`, I wanted to re-use the previous UUID. (The old file system will cease to exist, so duplication is not an issue.)

The help states

```
--volume-guid=guid                                Set volume GUID
```

It seems that the format for the -U / --volume-guid option is undocumented. Neither in help, nor in the manpage. A google search did not lead to any insight either.

Please state the acceptable format in the manpage.

I tried both "AAAA-BBBB" (as returned by `blkid`) and "AAAABBBB", but the program rejected both:

```sh
$ sudo lsblk /dev/loop7p1
/dev/loop7p1: LABEL="Daten" UUID="AAAA-BBBB" BLOCK_SIZE="512" TYPE="exfat" PARTUUID="662493fb-01"
$ sudo mkfs.exfat -L Daten -U AAAA-BBBB /dev/sde1
exfatprogs version : 1.2.5
Creating exFAT filesystem(/dev/sde1, cluster size=131072)

Writing volume boot record: done
Writing backup volume boot record: done
Fat table creation: done
Allocation bitmap creation: done
Upcase table creation: done
invalid format for volume guid
Writing root directory entry: failed

exFAT format fail!
 
$ sudo mkfs.exfat -L Daten -U AAAABBBB /dev/sde1
exfatprogs version : 1.2.5
Creating exFAT filesystem(/dev/sde1, cluster size=131072)

Writing volume boot record: done
Writing backup volume boot record: done
Fat table creation: done
Allocation bitmap creation: done
Upcase table creation: done
invalid format for volume guid
Writing root directory entry: failed

exFAT format fail!
```

**Comment by hclee** [comment]
exfat does not support uuid. exfat's volume GUID is different with uuid.
how about using partuuid instead of filesystem's uuid?

**Comment by luziferius** [comment]
I updated the fstab on the affected systems when setting the UUID failed. It wasn't that big of a deal. The partuuid also changed (I replaced a drive with a 4k native SSD, so had to redo all file systems and the partition table. I wanted to keep all used UUIDs in place so that bootloader files and similar can keep working without regenerating. And that worked in the end.)

Still, the format is udocumented. And if the GUID is distinct from the UUID reported by Linux and cannot be used to set the UUID suitable for the UUID identifier used in `fstab`, this detail should be in the man page. `blkid` does report an 8 character UUID for exfat volumes, and that has to come from somewhere.

I traced the validation logic down to https://github.com/exfatprogs/exfatprogs/blob/master/lib/libexfat.c#L536 . I'll try to understand what formats pass that validation and experiment with it. The open question for me is if setting a GUID does change the UUID reported by `blkid`. I think I'll open a PR to update the man page with the findings.

**Comment by hclee** [comment]
Please refer to a page below for the format of GUID
https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#101-globally-unique-identifiers-guids

And appreciate if you update the manpage

**Comment by namjaejeon** [comment]
@luziferius You seems to create the patch in your repo for this. Do you have a plan to contribute it to exfatprogs mainline ?

**Comment by luziferius** [comment]
I've edited the file through the GitHub interface and I'm pretty sure I opened a PR. When I checked back later, it seems to have vanished? (Totally not sure what happened) I closed when I saw that the PR is not in the opened or merged PR list.

**Comment by namjaejeon** [comment]
@luziferius Thanks for your contribution:), Applied your patch to #exfat-next now. Please close issue if there is no more issue.
