### ISSUE TITLE
[Documentation] Would it be possible to add a paragraph explaining the use case or reason for exfat-utils to exist, in the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [exfatprogs/exfatprogs#46]
Hello Namjae Jeon,

I recently read about exfat-utils on reddit, so I landed here. I do not know much else
about the project, which brought me to this question:

- Do you think it would be possible to add a very short paragraph, on the main
README.md of the project, explaining the main use case or motivation for
exfat-utils?

Right now I wonder about how exfat-utils fits into the rest of the toolchain
e. g. e2fsprogs, util-linux and so forth. Hope I could explain the reason for my
question here.

Thanks for your time!

**Comment by namjaejeon** [comment]
Sorry for late response. I will update it on this weekends.
Thanks for your feedback!

**Comment by namjaejeon** [comment]
@rubyFeedback Could you please review this paragraph ? Is it enough for you to expect ?
'''
## exfatprogs
As new exfat filesystem is merged into linux-5.7 kernel, exfatprogs is
an official userspace utilities that contain all of the standard utilities
for creating and fixing and debugging exfat filesystem in linux system.
exfatprogress is the goal of providing high performance and windows level
outstanding utils compared to old utils. And this software is licensed
under the GNU General Public License Version 2.
'''

**Comment by namjaejeon** [comment]
Pushed it(https://github.com/exfatprogs/exfatprogs/commit/47ad5d6491fafd67fc4fe59e9fcac6982447e3b6) to #exfat-next.
