### ISSUE TITLE
Install a header file to be able to link against libexfat.so

### ISSUE THREAD

**Issue by ismail** [exfatprogs/exfatprogs#61]
The source package when built provides libexfat.so but this is useless unless there is some public header/pkgconfig file to consume this library.

**Comment by namjaejeon** [comment]
Hi,
Acutally I didn't understand what is issue you raise. Can you send the patch to fix it ?
Thanks!

**Comment by ismail** [comment]
> Hi,
> Acutally I didn't understand what is issue you raise. Can you send the patch to fix it ?

It depends on what you want actually. Do you want people to link against libexfat.so and develop their own stuff? Then it needs to install the header files.

If you don't want to people develop against libexfat.so then easiest solution is to skip installing libexfat.so itself and only install the versioned library (libexfat.so.0*)

**Comment by namjaejeon** [comment]
@ismail Pushed the patch(https://github.com/exfatprogs/exfatprogs/commit/27cacf4aa1e16ebcbefee40ff14d854670d6c874) to #next. Thanks!

**Comment by ismail** [comment]
This looks nice, libexfat is statically linked but I don't see a downside to that.

**Comment by namjaejeon** [comment]
BTW... libexfat should shared linked at default ? and if user want to build with static linking, use -static option.

**Comment by ismail** [comment]
> BTW... libexfat should shared linked by default ? and if user want to build with static linking, use -static option.

As long as you don't want users to depend on it, I don't see a need for public libexfat.

**Comment by ismail** [comment]
This is fixed now.
