### ISSUE TITLE
fsck.c:1213:9: error: missing braces around initializer

### ISSUE THREAD

**Issue by jameshilliard** [exfatprogs/exfatprogs#74]
I'm seeing this build error [here](http://autobuild.buildroot.net/results/93ae73969904acb9a8a1b39e5bc9c940ec163295/build-end.log).
```c
  CC       repair.o
fsck.c: In function 'main':
fsck.c:1213:9: error: missing braces around initializer [-Werror=missing-braces]
  struct fsck_user_input ui = {0,};
         ^
fsck.c:1213:9: error: (near initialization for 'ui.ei') [-Werror=missing-braces]
fsck.c: At top level:
ccc

**Comment by namjaejeon** [comment]
The patch(https://github.com/exfatprogs/exfatprogs/commit/b0519f4fa7ce513d65d0f94c4d5a05be42730e7d) for this is already in exfat-Text.
